version: "3.8"

volumes:
    database-data:
        driver: local

networks:
    application-network:
        driver: bridge

services:
    database-service:
        image: postgres:latest
        container_name: database-service
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - application-network
